### ISSUE TITLE
zero tracks?

### ISSUE THREAD

**Issue by gingerlime** [hexiro/spotify-to-musi#12]
Thanks for creating spotify-to-musi. I'm having trouble importing tracks into musi however. The playlist gets imported and I can see the playlist and image in musi, but always with zero tracks

```
$ spotify-to-musi transfer --playlist https://open.spotify.com/playlist/3UhlWCPM8wFFmAESUcqQRg
SPOTIFY: Loaded Playlist () [0 tracks]
YOUTUBE: Loaded Playlist ()
Querying Spotify [ Playlists ] ...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Querying Spotify [ Playlist Tracks ] ... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Querying YouTube...                      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
MUSI CODE: 2a45vez
MUSI IMPORT:: MERGE
```

Is the problem with `spotify-to-musi` or with the musi restore?

**Comment by hexiro** [comment]
Hi! Sorry about this! I noticed this issue a little while ago but haven't found a solution yet.

From this line:
```
SPOTIFY: Loaded Playlist () [0 tracks]
```
We can see that Spotify isn't fetching any tracks, and I believe the root cause is the async spotify package, `pyfy`, which hasn't been updated in ~2 years, Although I'm not exactly sure what broke. With that being said, there aren't any other good options for async Spotify packages (as far as I'm aware), and Implementing Spotify's OAuth will be a pain. If you'd like to fix this issue, feel free, otherwise I'll try and get around to it as soon as I can.

**Comment by hexiro** [comment]
nope! I just did some proper digging and the issue was an oversight on my end, will push a fix soon.
